services:
- name: appaxyomisx
  region: Ohio (US East)
  plan: free
  buildCommand: pnpm install && pnpm run render-build
  buildCommandOnRestart: pnpm install && pnpm run render-build
  rootDirectory: artifacts/axyomis
  startCommand: pnpm --filter axyomis exec serve -s dist/public
  repo: https://github.com/sahilkarnainternational-ctrl/appaxyomisx
  branch: main
  autoDeployHook: https://api.render.com/deploy/trigger/••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
  env:
  - name: NODE_VERSION
    value: 22.13.0
  - name: GEMINI_API_KEY
    sync: false
  - name: BASE_PATH
    value: /
  - name: NODE_ENV
    value: production
kind:Webservice
yamlVersion:1