/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
// Data Sets
export const DATA_SETS = {
    Nature: "Solar System,Life,Plant reproduction,Water cycle,Atmosphere of Earth,Photosynthesis,Mammal,Bird,Reptile,Amphibian,Fish,Insect".split(","),
    Fruits: "Apple,Banana,Orange,Mango,Pineapple,Grapes,Watermelon,Strawberry,Blueberry,Kiwifruit,Peach,Plum,Cherry,Pear,Papaya,Pomegranate,Lemon,Coconut,Guava,Avocado".split(","),
    Vegetables: "Tomato,Potato,Carrot,Broccoli,Spinach,Cabbage,Onion,Garlic,Ginger,Radish,Cucumber,Pumpkin,Eggplant,Bell pepper,Maize,Pea,Bean,Lentil,Soybean".split(","),
    Hygiene: "Drinking water,Soap,Toothbrush,Toothpaste,Towel,Comb,Shampoo,Hand sanitizer,Dental floss,Nail clipper".split(","),
    Physics: "Classical mechanics,Kinematics,Newton's laws of motion,Gravity,Work (physics),Energy,Power (physics),Momentum,Torque,Fluid mechanics,Bernoulli's principle,Thermodynamics,Entropy,Electromagnetism,Electric charge,Magnetic field,Maxwell's equations,Optics,Refraction,Diffraction,Quantum mechanics,Schrödinger equation,Heisenberg uncertainty principle,Theory of relativity,Special relativity,Nuclear physics,Radioactivity,Astrophysics,Black hole,Cosmology,String theory".split(","),
    Chemistry: "Atomic theory,Electron configuration,Periodic table,Chemical bond,Covalent bond,Ionic bond,Intermolecular force,Chemical reaction,Stoichiometry,Acid–base reaction,Redox,Chemical equilibrium,Chemical kinetics,Chemical thermodynamics,Electrochemistry,Organic chemistry,Alkane,Alkene,Alcohol,Carboxylic acid,Amine,Polymer,Biochemistry,Protein,Carbohydrate,Lipid,Nucleic acid,Enzyme,Metabolism,Ideal gas law,Spectroscopy,Chromatography".split(","),
    Biology: "Cell (biology),Organelle,Cell nucleus,Mitochondrion,Chloroplast,Cell membrane,Ribosome,Lysosome,Cell cycle,Mitosis,Meiosis,Genetics,DNA,RNA,Gene,Chromosome,Mutation,Transcription (biology),Translation (biology),Epigenetics,Evolution,Natural selection,Phylogeny,Ecology,Ecosystem,Food web,Biome,Tree,Anatomy,Physiology,Nervous system,Cardiovascular system,Respiratory system,Endocrine system,Immune system,Botany,Photosynthesis,Microbiology,Bacteria,Virus,Fungi,CRISPR,Stem cell".split(","),
    Mathematics: "Calculus,Algebra,Trigonometry,Pythagorean theorem,Euler's formula,Integral,Derivative,Linear algebra,Probability,Statistics,Differential equation,Quadratic equation,Taylor series,Fourier transform,Complex number,Matrix (mathematics),Vector space,Logarithm".split(","),
    diseases: "Malaria,Dengue fever,Tuberculosis,Cholera,Typhoid fever,HIV/AIDS,COVID-19,Influenza,Pneumonia,Measles,Rubella,Polio,Tetanus,Rabies,Leprosy,Leishmaniasis,Lymphatic filariasis,Asthma,Chronic obstructive pulmonary disease,Lung cancer,Breast cancer,Prostate cancer,Colorectal cancer,Leukemia,Lymphoma,Melanoma,Diabetes,Hypertension,Coronary artery disease,Stroke,Heart failure,Alzheimer's disease,Parkinson's disease,Epilepsy,Schizophrenia,Bipolar disorder,Osteoarthritis,Rheumatoid arthritis,Osteoporosis,Gout,Cirrhosis,Appendicitis,Crohn's disease,Celiac disease,Chronic kidney disease,Anemia,Hemophilia,Sickle cell disease,Down syndrome,Cystic fibrosis,Malnutrition,Scurvy,Rickets,Kwashiorkor,Obesity,Toxoplasmosis,Giardiasis,Amoebiasis,Ascariasis,Scabies".split(",")
};
export const WIKI_MAP = {
    "Life": "Life (biology)", "Plant reproduction": "Plant reproduction", "Living Things": "Life", "Solar System": "Solar System",
    "Water cycle": "Water cycle", "Atmosphere of Earth": "Atmosphere of Earth", "Photosynthesis": "Photosynthesis",
    "Apple": "Apple", "Orange": "Orange (fruit)", "Lemon": "Lemon", "Lime": "Lime (fruit)", "Pea": "Pea",
    "Kiwi": "Kiwifruit", "Kiwifruit": "Kiwifruit", "Work": "Work (physics)", "Energy": "Energy",
    "Power": "Power (physics)", "Mercury": "Mercury (element)", "Lead": "Lead", "Mole": "Mole (unit)", "Cell": "Cell (biology)",
    "Mammal": "Mammal", "Bird": "Bird", "Reptile": "Reptile", "Amphibian": "Amphibian", "Fish": "Fish", "Insect": "Insect",
    "Classical mechanics": "Classical mechanics", "Newton's laws of motion": "Newton's laws of motion",
    "Gravity": "Gravity", "Flux": "Flux", "Acid–base reaction": "Acid–base reaction", "Redox": "Redox",
    "Cell cycle": "Cell cycle", "Mitosis": "Mitosis", "Meiosis": "Meiosis", "DNA": "DNA", "RNA": "RNA",
    "Kinematics": "Kinematics", "Dynamics": "Dynamics", "Statics": "Statics", "Thermodynamics": "Thermodynamics",
    "Optics": "Optics", "Magnetism": "Magnetism", "Electricity": "Electricity", "Atomic physics": "Atomic physics"
};
export const FORMULA_MAP = {
    "Newton's laws of motion": "Force & Acceleration:<br>$$ \\mathbf{F} = \\frac{d\\mathbf{p}}{dt} = m\\mathbf{a} $$",
    "Gravity": "Newton's Law of Universal Gravitation:<br>$$ F = G \\frac{m_1 m_2}{r^2} $$",
    "Thermodynamics": "First Law of Thermodynamics:<br>$$ \\Delta U = Q - W $$",
    "Entropy": "Boltzmann's Entropy Formula:<br>$$ S = k_B \\ln \\Omega $$",
    "Maxwell's equations": "Gauss's Law & Faraday's Law:<br>$$ \\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\varepsilon_0} \\quad \\text{and} \\quad \\nabla \\times \\mathbf{E} = -\\frac{\\partial \\mathbf{B}}{\\partial t} $$",
    "Schrödinger equation": "Time-dependent Formulation:<br>$$ i\\hbar \\frac{\\partial}{\\partial t}\\Psi(\\mathbf{r},t) = \\hat{H}\\Psi(\\mathbf{r},t) $$",
    "Theory of relativity": "Mass-Energy Equivalence:<br>$$ E = mc^2 $$",
    "Ideal gas law": "Equation of State:<br>$$ PV = nRT $$",
    "Acid–base reaction": "pH Calculation:<br>$$ \\text{pH} = -\\log_{10}[\\text{H}^+] $$",
    "Photosynthesis": "Overall Chemical Equation:<br>$$ 6\\text{CO}_2 + 6\\text{H}_2\\text{O} + \\text{light} \\rightarrow \\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2 $$",
    "Pythagorean theorem": "Right Triangle Relation:<br>$$ a^2 + b^2 = c^2 $$",
    "Calculus": "Fundamental Theorem of Calculus:<br>$$ \\int_a^b f(x) dx = F(b) - F(a) $$"
};
export const COSMOS_DATA = {
    solar: { title: "Solar System", sfId: "600b747a80934238b7183b6c70b991e4", desc: `<h3><i class="fas fa-sun"></i> Chapter: Heliocentric Orbital Mechanics</h3><p>The solar system consists of our local star, the Sun, and all the astronomical bodies gravitationally bound within its immense heliosphere. This module explores planetary orbits, the Kuiper Belt, and the Oort Cloud, providing a comprehensive look at our celestial neighborhood.</p>` },
    sun: { title: "Supernova Explosion", sfId: "b4a7ae96dbd944708e4023645620014d", desc: `<h3><i class="fas fa-star-of-life"></i> Chapter: Terminal Stellar Nucleosynthesis</h3><p>A supernova is the incredibly luminous, catastrophic explosion of a supermassive star. This chapter covers the physics of stellar collapse, the creation of heavy elements, and the resulting pulsars or black holes that remain after the blast.</p>` },
    blackhole: { title: "Wormhole & Black Hole", sfId: "c26eff50075d460ab994a9847d92584c", desc: `<h3><i class="fas fa-circle-notch"></i> Chapter: Gravitational Singularities & Spacetime</h3><p>Black holes define regions of spacetime where gravitational acceleration is so intense that nothing can reach escape velocity. We examine event horizons, Hawking radiation, and the theoretical foundation of wormholes as bridges between spacetime coordinates.</p>` },
    earth: { title: "Earth", sfId: "5c83056b54cc41be84c554fb6404c7fd", desc: `<h3><i class="fas fa-globe-americas"></i> Chapter: The Habitable Biosphere</h3><p>Earth is defined by its protective molten iron core that generates a massive magnetosphere. Learn about tectonic plates, atmospheric composition, and the delicate carbon cycle that allows life to persist in a vacuum.</p>` },
    moon: { title: "The Moon", sfId: "870de693475d436c8e925ab0bcda4ca4", desc: `<h3><i class="fas fa-moon"></i> Chapter: Tidal Locking & Lunar Geology</h3><p>Earth's natural satellite remains status tidally locked. This module details the impact craters, the Maria (ancient lava basalt), and the gravitational influence the moon exerts on Earth's oceans and biological rhythms.</p>` },
    mars: { title: "Mars", sfId: "92a2da6525534a23a81e76ab1da4126d", desc: `<h3><i class="fas fa-rocket"></i> Chapter: The Iron Oxide Terrain</h3><p>Characterized by its stark, reddish iron oxide surface dust, Mars features the tallest known volcano, Olympus Mons. Study the possibilities of ancient water flows and the current atmosphere's thin carbon dioxide makeup.</p>` },
    jupiter: { title: "Jupiter", sfId: "71d39a0a6892498ab8b1c8f77feba842", desc: `<h3><i class="fas fa-meteor"></i> Chapter: The Gas Giant & Magnetospheres</h3><p>Jupiter is a massive gas giant primarily composed of compressed hydrogen and helium. Explore its Great Red Spot—a storm larger than Earth—and the complex moon system including Europa and Io.</p>` },
    saturn: { title: "Saturn", sfId: "0004ad33093b44ad8189747e03bfb2c0", desc: `<h3><i class="fas fa-ring"></i> Chapter: Orbital Ring Debris & Ice Physics</h3><p>Saturn is globally famous for its spectacular ring system. This chapter breaks down the composition of the rings—billions of individual ice crystals and rocks—and the moon Titan, which has its own atmosphere.</p>` },
    comet: { title: "Comet Dynamics", sfId: "fc0f8e88db8b46b286c223c1f5b578a0", desc: `<h3><i class="fas fa-icicles"></i> Chapter: Sublimation & Ion Tails</h3><p>Comets are ancient cosmic snowballs of frozen gases, rock, and dust. Understand how they develop a visible coma and tail when they pass close to the Sun's solar winds.</p>` },
    asteroids: { title: "Asteroid Field", sfId: "bi6oZSkyn9f9QGgTAqq7GvaCohn", desc: `<h3><i class="fas fa-cubes"></i> Chapter: Primordial Cosmic Fragments</h3><p>Asteroids are the heavily cratered, rocky remnants left over from early formation of the solar system. Learn about the Asteroid Belt between Mars and Jupiter and the potential for deep-space mining.</p>` },
    meteor: { title: "Meteor Atmospheric Entry", sfId: "d3a5a7e9a7d24b76841bf0f49d56a5f3", desc: `<h3><i class="fas fa-fire"></i> Chapter: Atmospheric Ablation & Friction</h3><p>When a meteoroid enters Earth's atmosphere at hypersonic velocities, aerodynamic friction incinerates the rock. Study the thermodynamic process of ablation and the chemistry of meteor trails.</p>` },
    constellation: { title: "Constellation Mapping", sfId: "6ddc2ebd143141259ab42cbe3b1a0767", desc: `<h3><i class="fas fa-project-diagram"></i> Chapter: Stellar Cartography & Navigation</h3><p>Constellations are recognizable patterns of distant, highly luminous stars. This module covers traditional navigation methods and the modern use of constellations in mapping the celestial sphere.</p>` },
    telescope: { title: "Astronomy Telescope", sfId: "ccda49cff4574f62be87049e70b4fe38", desc: `<h3><i class="fas fa-search-plus"></i> Chapter: Optical Engineering & Photon Collection</h3><p>Optical telescopes utilize configurations of mirrors and lenses to resolve distant galaxies. Learn about focal lengths, aperture size, and the difference between reflecting and refracting systems.</p>` }
};
export const MICRO_DATA = {
    cell: { title: "Human Cell Animation", sfId: "daa4b42f6bb249d88a751c5aa0d2534c", desc: `<h3><i class="fas fa-circle"></i> Eukaryotic Cellular Biology</h3><p>The human cell operates as an incredibly complex, microscopic metropolis.</p>` },
    virus: { title: "SARS-CoV-2 (COVID-19)", sfId: "1533d2519b084a1580ddba0d3c5a3aff", desc: `<h3><i class="fas fa-virus"></i> Viral Pathology & Spike Proteins</h3><p>SARS-CoV-2 utilizes spike glycoproteins to aggressively bind to human ACE2 receptors.</p>` },
    neuron: { title: "Neural Network Anatomy", sfId: "8aeec8b603ce434fb150f957a55a94e1", desc: `<h3><i class="fas fa-network-wired"></i> Synaptic Transmission Dynamics</h3><p>Neurons are the heavily specialized, electrically excitable cells of the nervous system.</p>` },
    wound: { title: "Animated Wound Healing", sfId: "b23a19e950ef43449c204e8a08ef1d72", desc: `<h3><i class="fas fa-band-aid"></i> The Coagulation Cascade</h3><p>Immediate tissue trauma forcefully initiates an explosive biological response.</p>` },
    dino: { title: "Paleontology & Fossilization", sfId: "58f1dc316fc84b5786ffc40d18c4dcb0", desc: `<h3><i class="fas fa-bone"></i> Evolutionary Stratigraphy</h3><p>The meticulous unearthing of fossilized dinosaur remains reconstructs prehistoric ecosystems.</p>` }
};
export const ANATOMY_DATA = {
    internal: { title: "Internal Organs Anatomy", sfId: "8a43f3a308994699a4000b17004d5220", desc: `<h3><i class="fas fa-lungs"></i> Chapter: Systemic Interconnectivity</h3><p>Explore the full human torso. This chapter details exact spatial relationships between the thorax and abdomen, highlighting how organs are packed for maximum efficiency.</p>` },
    heart: { title: "Anatomical Human Heart", sfId: "e48637d3399a4e5184bdf169929dc36e", desc: `<h3><i class="fas fa-heartbeat"></i> Chapter: Myocardial Contraction & Hemodynamics</h3><p>Examine specialized internal valves, the sinoatrial node (the natural pacemaker), and the muscular ventricular walls that drive circulation throughout the body.</p>` },
    brain: { title: "Human Brain with Internal Structures", sfId: "95b4e19bb32c4edeb46fcb3db048037c", desc: `<h3><i class="fas fa-brain"></i> Chapter: Advanced Neurological Architecture</h3><p>Visualize the limbic system, hippocampus, and ventricular system. Understand the lobes of the brain and their specific roles in cognition, memory, and motor control.</p>` },
    lungs: { title: "Healthy Human Lungs", sfId: "ad1a6c31b37547fabfc9fe37af69796b", desc: `<h3><i class="fas fa-wind"></i> Chapter: Alveolar Gas Exchange & Respiration</h3><p>The branching bronchial tree maximizes surface area for oxygen absorption. Study the mechanism of the diaphragm and the physics of pleural pressure.</p>` },
    cardio: { title: "3D Cardiovascular System", sfId: "b285a0b16caf4bc888c282ea5cb6f411", desc: `<h3><i class="fas fa-tint"></i> Chapter: The Systemic Vascular Network</h3><p>A pressurized highway for distributing oxygen and immune cells. This chapter covers arteries, veins, and the microscopic capillary beds where gas exchange occurs.</p>` },
    vein: { title: "Vein + Artery Tour", sfId: "c26e0f2e75fe4087aa8c4ecee2cad1aa", desc: `<h3><i class="fas fa-water"></i> Chapter: Endothelial Micro-Anatomy</h3><p>Observe the three-layered walls of arteries versus the thinner, valve-equipped veins. Learn about the biomechanics of pulse waves and venous return.</p>` },
    head: { title: "Head Anatomy & Musculature", sfId: "b018e3f215c14be6ab5c52e5371c3ba5", desc: `<h3><i class="fas fa-smile"></i> Chapter: Complex Craniofacial Layers</h3><p>Explore the 43 mimesis muscles of the face and the underlying cranial bones. Study the innervation of the facial nerve and the structures of the jaw.</p>` },
    facial: { title: "Ecorche Facial Anatomy", sfId: "c23ad54a770244a6a0067fe86c9c410b", desc: `<h3><i class="fas fa-user"></i> Chapter: The Classic Medical Ecorche</h3><p>Exposed geometry of subcutaneous fat pads and vascularized structures. This module is essential for understanding the relationship between bone, muscle, and skin surfaces.</p>` },
    liver: { title: "3D Human Liver Anatomy", sfId: "a20686a3e4a54792bfede17ad32f4b1a", desc: `<h3><i class="fas fa-filter"></i> Chapter: Metabolic Filtration & Detoxification</h3><p>The liver is the body's primary chemical refinery. Study its lobular structure, the production of bile, and its role in regulating blood glucose levels.</p>` },
    urinary: { title: "Urinary System", sfId: "fbdc1d3b14454cacbf353ba21246b7b2", desc: `<h3><i class="fas fa-vial"></i> Chapter: Renal Filtration & Homeostasis</h3><p>Kidneys utilize millions of nephrons to filter the entire blood supply every 5 minutes. Learn about the loop of Henle and fluid electrolyte balance.</p>` },
    malerepro: { title: "Male Reproductive & Urinary System", sfId: "2c04bed82f2445b5ad0211bfa9e893c4", desc: `<h3><i class="fas fa-mars"></i> Chapter: Pelvic Floor & Excretory Architecture</h3><p>Detailed model of excretory and reproductive architecture proximity. Understand the structural relationship between the bladder, prostate, and urethra.</p>` },
    woman: { title: "Animated Woman Body Anatomy", sfId: "b62a790eacba45bba09218f27925c92f", desc: `<h3><i class="fas fa-venus"></i> Chapter: Female Systemic Architecture</h3><p>Examine skeletal proportions and pelvic girdle adaptations specific to the female framework, alongside the integrated endocrine and reproductive systems.</p>` },
    uterus: { title: "Uterus Shedding", sfId: "a51369ed5c5549f99c24164850a1fc67", desc: `<h3><i class="fas fa-tint-slash"></i> Chapter: Endometrial Cycle & Hormonal Flux</h3><p>The catalytic ischemic breakdown of vascularized uterine lining. Study the phases of the menstrual cycle—follicular, ovulatory, and luteal.</p>` },
    fetus: { title: "Human Embryonic & Fetal Stages", sfId: "9fb225b983c14b20b67b639e17126f5b", desc: `<h3><i class="fas fa-baby"></i> Chapter: Embryogenesis & Fetal Proliferation</h3><p>Witness the transition from embryonic cluster to fully formed fetus. This chapter tracks organ systems development from the 3rd week to the 40th week of gestation.</p>` }
};
export const HOSPITAL_DATA = {
    recovery: { title: "Hospital Recovery Room", sfId: "eaca09ed02ba401f8728113e17a2ce3b", desc: `<h3><i class="fas fa-bed"></i> Chapter: Post-Anesthesia Care Unit (PACU)</h3><p>Study the standard setup for continuous vital telemetry. Learn how patients are monitored for post-operative complications and the layout of life-support equipment.</p>` },
    autopsy: { title: "Autopsy Lab Assets", sfId: "5ceaaa4482a84774b9922366cfb228e7", desc: `<h3><i class="fas fa-skull"></i> Chapter: Forensic Pathology & Post-Mortem Exams</h3><p>A hyper-sterile environment for clinical morbid anatomy dissection. Explore the specific tools used in forensic investigation and the layout of a modern morgue.</p>` },
    dental: { title: "Dental Clinic", sfId: "8d1b28daf13643488cbca29a465e23c8", desc: `<h3><i class="fas fa-tooth"></i> Chapter: Maxillofacial & Periodontic Setup</h3><p>The specialized environment for dental surgery. Study the ergonomics of the dental chair, suction systems, and high-speed precision drills.</p>` },
    anesthesia: { title: "Anesthesia Machine", sfId: "67841aa7eed745b8b438d5a22b560900", desc: `<h3><i class="fas fa-gas-pump"></i> Chapter: Volatile Gas Delivery Systems</h3><p>Understand the engineering behind mixing oxygen with volatile anesthetic gases. Learn about vaporizers, soda lime canisters, and mechanical ventilation loops.</p>` },
    infusion: { title: "Medical Infusion Stand", sfId: "52fbb1f1a64f4bc78055fd3f8437a611", desc: `<h3><i class="fas fa-prescription-bottle-alt"></i> Chapter: Intravenous Fluid Dynamics</h3><p>Automated delivery of potent vasopressors and antibiotics. Study how infusion pumps maintain steady-state plasma concentrations of critical medications.</p>` },
    portablexray: { title: "Portable X-Ray Machine", sfId: "13ec391d3ff74e7ba0c26de06156d5fd", desc: `<h3><i class="fas fa-x-ray"></i> Chapter: Bedside Radiography Mechanics</h3><p>Ionizing radiation imaging directly at the bedside. Explore the mechanics of the X-ray tube and the safety protocols required for mobile imaging.</p>` },
    xrayviewer: { title: "Medical X-ray Image Viewer", sfId: "1caaa90f0e6b48d08109e517ddd8aab0", desc: `<h3><i class="fas fa-film"></i> Chapter: Radiographic Density & Diagnosis</h3><p>High-contrast medical lightboxes for structural analysis. Learn how to identify bone fractures, pleural effusions, and anatomical anomalies on X-ray films.</p>` },
    equipments: { title: "Medical Equipments", sfId: "0fb5375292954f778f42d66d490565a4", desc: `<h3><i class="fas fa-stethoscope"></i> Chapter: Clinical Hardware Integration</h3><p>Overview of sterilized stainless steel instruments and critical multi-parameter monitors used in every modern hospital setup.</p>` },
    lighting: { title: "Surgical Lighting Showroom", sfId: "9681d607bfda442499b96f9655c80c86", desc: `<h3><i class="fas fa-lightbulb"></i> Chapter: Shadowless LED Illumination</h3><p>Study the optics used to eliminate shadows during deep-cavity surgery. Contrast cold-light LED technology with traditional halogen surgical lamps.</p>` },
    syringe: { title: "Syringe with Animations", sfId: "f1b341e942d24d8d846cd42bf4bea4f1", desc: `<h3><i class="fas fa-syringe"></i> Chapter: Hypodermic Injection Physics</h3><p>The mechanical tool for breaching the dermal barrier. Study the difference between intramuscular, subcutaneous, and intravenous needle angles and pressures.</p>` },
    nurse: { title: "Animated Medical Nurse", sfId: "aee80c66dba94b28a625a1eb05fdcbe6", desc: `<h3><i class="fas fa-user-nurse"></i> Chapter: Clinical Vigilance & Vital Monitoring</h3><p>Examine the workflow of frontline healthcare professionals, focusing on vital sign assessment, medication administration, and patient safety algorithms.</p>` }
};
