"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const pino_http_1 = __importDefault(require("pino-http"));
const logger_1 = require("./lib/logger");
const chat_1 = __importDefault(require("./routes/chat"));
const youtube_1 = __importDefault(require("./routes/youtube"));
const email_1 = __importDefault(require("./routes/email"));
const health_1 = __importDefault(require("./routes/health"));
const app = (0, express_1.default)();
app.use((0, pino_http_1.default)({ logger: logger_1.logger }));
app.use((0, cors_1.default)({ origin: true }));
app.use(express_1.default.json());
app.use("/api/chat", chat_1.default);
app.use("/api", youtube_1.default);
app.use("/api/email", email_1.default);
app.use("/api/health", health_1.default);
exports.default = app;
